### ISSUE TITLE
R16B03-1 Travis PLT

### ISSUE THREAD

**Issue by joedevivo** [esl/erlang-plts#1]
This is great! Could you generate a plt for R16B03-1 on travis? thanks

**Comment by erszcz** [comment]
I've added a PLT for R16B03-1 with 0466df2.
Please note that after a while we decided to build the PLT during each Travis job for our projects. However, if you prefer to fetch prebuilt PLTs then the repo is going to stay here for the foreseeable future.

**Comment by joedevivo** [comment]
Take a look at what we're doing in opscode/concrete, specifically: https://github.com/opscode/concrete/blob/master/priv/templates/concrete_project_concrete.mk#L154-L181

We're pulling in the base plt, and then building the app's specific dependencies as a separate plt. cuts down the build time for travis.

Anyway, thanks for this, I'll close the issue.
